# Generated by Django 3.0.3 on 2020-05-25 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_app', '0002_auto_20200524_1256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salary',
            old_name='dbaExp',
            new_name='dbaSen',
        ),
        migrations.RenameField(
            model_name='salary',
            old_name='sweExp',
            new_name='sweSen',
        ),
        migrations.RenameField(
            model_name='salary',
            old_name='webExp',
            new_name='webSen',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='sweMid',
        ),
        migrations.AddField(
            model_name='salary',
            name='swesMid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='city',
            name='col_index',
            field=models.DecimalField(decimal_places=3, max_digits=4),
        ),
    ]
