# Generated by Django 3.0.3 on 2020-05-25 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_app', '0003_auto_20200525_1158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salary',
            old_name='swesMid',
            new_name='sweMid',
        ),
    ]
